services:
  aiohttp:
    build: .
    command: ["gunicorn", "aiohttp_:app", "-k=aiohttp.GunicornUVLoopWebWorker"]
    network_mode: host

  blacksheep:
    build: .
    command: ["uvicorn", "blacksheep_:app", "--no-access-log"]
    network_mode: host

  emmett:
    build:
      dockerfile: emm.Dockerfile
    command: ["emmett", "-aemmett_.py", "serve"]
    network_mode: host

  fastapi:
    build: .
    command: ["uvicorn", "fastapi_:app", "--no-access-log"]
    network_mode: host

  muffin:
    build: .
    command: ["uvicorn", "muffin_:app", "--no-access-log"]
    network_mode: host

  robyn:
    build: .
    command: ["python", "robyn_.py", "--log-level=WARN"]
    network_mode: host

  sanic:
    build: .
    command: ["sanic", "sanic_:app", "--single-process", "--no-access-logs"]
    network_mode: host

  starlette:
    build: .
    command: ["uvicorn", "starlette_:app", "--no-access-log"]
    network_mode: host

  granian:
    build: 
      dockerfile: emm.Dockerfile
    command: ["granian", "granian_:app"]
    network_mode: host

  uvicorn:
    build: .
    command: ["uvicorn", "uvicorn_:app", "--no-access-log"]
    network_mode: host
